name: Dependency Analysis
on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Check environment compatibility
        run: |
          node -v
          pnpm -v

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check for dependency issues
        run: |
          pnpm add -D depcheck
          npx depcheck --pnpm
          pnpm install --check-lockfile --strict-peer-dependencies
          pnpm store status
          pnpm tree --duplicates
          pnpm check --verify-store-integrity
          pnpm install --dry-run --frozen-lockfile
        continue-on-error: false

      - name: Dependency security scan
        run: |
          pnpm audit
          pnpm add -D snyk
          npx snyk test --strict-out-of-sync=false --strict-semver=false
        continue-on-error: true

      - name: Generate dependency reports
        run: |
          pnpm add -D dependency-cruiser webpack-bundle-analyzer
          npx dependency-cruiser src --output-type dot | dot -Tsvg > dependencies.svg
          if [ -f "webpack.config.js" ]; then
            npx webpack --json > dist/stats.json
            npx webpack-bundle-analyzer dist/stats.json --mode static --reportFilename bundle-analysis.html
          fi
        continue-on-error: true
        if: always()

      - name: Upload dependency reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-reports
          path: |
            dependencies.svg
            bundle-analysis.html
        if: always()